CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE IF NOT EXISTS core.contractedorg (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  "number" NUMERIC NOT NULL,
  name TEXT NOT NULL UNIQUE,
  usercount BIGINT NOT NULL CHECK (usercount >= 0),
  businessregion NUMERIC,
  businesstype NUMERIC,
  data JSONB NOT NULL,
  status BOOLEAN NOT NULL DEFAULT true
);

ALTER TABLE core.contractedorg
  ADD COLUMN IF NOT EXISTS businessregion NUMERIC;

ALTER TABLE core.contractedorg
  ADD COLUMN IF NOT EXISTS businesstype NUMERIC;

CREATE INDEX IF NOT EXISTS contractedorg_status_idx ON core.contractedorg (status);
CREATE INDEX IF NOT EXISTS contractedorg_number_idx ON core.contractedorg ("number");
CREATE INDEX IF NOT EXISTS contractedorg_data_gin_idx ON core.contractedorg USING GIN (data);
