CREATE SCHEMA IF NOT EXISTS core;

CREATE TABLE IF NOT EXISTS core.contractedorg (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  "number" NUMERIC NOT NULL,
  name TEXT NOT NULL UNIQUE,
  usercount BIGINT NOT NULL CHECK (usercount >= 0),
  businessregion NUMERIC,
  businesstype NUMERIC,
  data JSONB NOT NULL,
  status BOOLEAN NOT NULL DEFAULT true
);

ALTER TABLE core.contractedorg
  ADD COLUMN IF NOT EXISTS businessregion NUMERIC;

ALTER TABLE core.contractedorg
  ADD COLUMN IF NOT EXISTS businesstype NUMERIC;

CREATE INDEX IF NOT EXISTS contractedorg_status_idx ON core.contractedorg (status);
CREATE INDEX IF NOT EXISTS contractedorg_number_idx ON core.contractedorg ("number");
CREATE INDEX IF NOT EXISTS contractedorg_data_gin_idx ON core.contractedorg USING GIN (data);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

SELECT set_config('app.schema_name', :'schema_name', false);

DO $$
DECLARE
  target_schema text := current_setting('app.schema_name', true);
BEGIN
  IF target_schema IS NULL OR btrim(target_schema) = '' THEN
    RAISE NOTICE 'schema_name was not provided; skipping organization schema DDL';
    RETURN;
  END IF;

  target_schema := btrim(target_schema);

  IF target_schema !~ '^[A-Za-z_][A-Za-z0-9_]{0,62}$' THEN
    RAISE EXCEPTION 'schema_name must be a valid PostgreSQL identifier: %', target_schema;
  END IF;

  EXECUTE format('CREATE SCHEMA IF NOT EXISTS %I', target_schema);

  IF lower(target_schema) LIKE 'trawlerowner%' THEN
    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.auction (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        auctionid text null,
        journeyid text null,
        date date null,
        constraint auction_pkey primary key (id)
      ) TABLESPACE pg_default',
      target_schema
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.auctiondetails (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        auctionid text null,
        traynumber bigint null,
        earning double precision null,
        buyerid numeric null,
        startingprice double precision null,
        grossweight double precision null,
        constraint auctiondetails_pkey primary key (id)
      ) TABLESPACE pg_default',
      target_schema
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I."group" (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        sellerid bigint null,
        status boolean null,
        constraint group_pkey primary key (id)
      ) TABLESPACE pg_default',
      target_schema
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.journeycost (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        resource bigint null,
        cost double precision null,
        journeyid uuid null default gen_random_uuid(),
        advance double precision null,
        name text null,
        phone numeric null,
        constraint journeycost_pkey primary key (id)
      ) TABLESPACE pg_default',
      target_schema
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.journeyinfo (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        trawlernumber text null,
        startdate date null,
        "return" date null,
        journeyid uuid null default gen_random_uuid(),
        headcount bigint null,
        constraint journeyinfo_pkey primary key (id)
      ) TABLESPACE pg_default',
      target_schema
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.journeyledger (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        journeyid uuid null default gen_random_uuid(),
        journeycost double precision null,
        auctionearning double precision null,
        constraint journeyledger_pkey primary key (id)
      ) TABLESPACE pg_default',
      target_schema
    );

    EXECUTE format(
      'CREATE TABLE IF NOT EXISTS %I.trawlermaster (
        id bigint generated by default as identity not null,
        created_at timestamp with time zone not null default now(),
        number text null,
        name text null,
        type bigint null,
        constraint trawlermaster_pkey primary key (id)
      ) TABLESPACE pg_default',
      target_schema
    );
  END IF;
END $$;
